./ldapuser1.mfs.cp.sh: line 1: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 2: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 3: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 4: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 5: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 6: hadoop: command not found

./ldapuser1.mfs.cp.sh: line 8: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 9: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 10: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 11: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 12: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 13: hadoop: command not found

./ldapuser1.mfs.cp.sh: line 15: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 16: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 17: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 18: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 19: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 20: hadoop: command not found

./ldapuser1.mfs.cp.sh: line 22: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 23: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 24: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 25: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 26: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 27: hadoop: command not found

./ldapuser1.mfs.cp.sh: line 29: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 30: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 31: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 32: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 33: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 34: hadoop: command not found

./ldapuser1.mfs.cp.sh: line 36: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 37: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 38: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 39: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 40: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 41: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 43: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 44: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 45: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 46: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 47: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 48: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 49: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 50: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 51: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 52: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 53: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 54: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 55: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 56: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 57: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 58: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 59: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 60: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 61: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 62: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 63: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 64: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 65: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 66: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 67: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 68: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 69: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 70: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 71: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 72: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 73: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 74: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 75: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 76: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 77: hadoop: command not found
./ldapuser1.mfs.cp.sh: line 78: hadoop: command not found
