set `store.parquet.reader.int96_as_timestamp`=true;
analyze table `table_stats/alltypes_with_nulls` compute statistics;
analyze table `table_stats/date_intervals` compute statistics;
analyze table `table_stats/impala_parquet` compute statistics;
analyze table `table_stats/DRILL-4735` compute statistics;
analyze table `table_stats/inNstedDirAutoPrtn` compute statistics;
refresh table metadata `table_stats/lineitem_parquet_partitioned_hive_date`;
analyze table `table_stats/lineitem_parquet_partitioned_hive_date` compute statistics;
analyze table `table_stats/parquet_alltypes1` compute statistics;
analyze table `table_stats/parquet_alot_nulls` compute statistics;
analyze table `table_stats/parquet_col_empty` compute statistics;
analyze table `table_stats/parquet_col_nulls` compute statistics;
analyze table `table_stats/ps_5level` compute statistics;
analyze table `table_stats/spark_generated` compute statistics;
analyze table `table_stats/voter_hive_parquet` compute statistics;
analyze table `table_stats/hive_alltypes` compute statistics (c1,c2,c3,c4,c9,c10,c11,c12,n);
--analyze table `table_stats/data_with_0` compute statistics (non_exist_col,bigint_col,bigint_col,int_col,bigint_col);
analyze table `table_stats/data_with_0` compute statistics (int_col,bigint_col);
analyze table `table_stats/nested_scalar_cols` compute statistics(glossary.title,glossary.GlossDiv.title,glossary.GlossDiv.GlossList.GlossEntry.Acronym,glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlso[0]);
analyze table `table_stats/Tpch0.01/parquet/customer` compute statistics;
analyze table `table_stats/Tpch0.01/parquet/part` compute statistics;
analyze table `table_stats/Tpch0.01/parquet/partsupp` compute statistics;
analyze table  `table_stats/empty` compute statistics;
--tests with partition pruning
analyze table `table_stats/pp_some_cols/1991/1` compute statistics(p_name,p_type,p_size);
analyze table `table_stats/pp_some_cols` compute statistics(p_name,p_type,p_size);
analyze table  `table_stats/pp_some_cols/1992/2/1/2` compute statistics(p_name,p_type,p_size,p_retailprice);
reset `store.parquet.reader.int96_as_timestamp`;
