USA	CA	Drink	F
USA	CA	Drink	M
USA	CA	Food	F
USA	CA	Food	M
USA	CA	Non-Consumable	F
USA	CA	Non-Consumable	M
USA	OR	Drink	F
USA	OR	Drink	M
USA	OR	Food	F
USA	OR	Food	M
USA	OR	Non-Consumable	F
USA	OR	Non-Consumable	M
USA	WA	Drink	F
USA	WA	Drink	M
USA	WA	Food	F
USA	WA	Food	M
USA	WA	Non-Consumable	F
USA	WA	Non-Consumable	M
