79	Bakhtyari	Mary Bakhtyari	Mary
77	Brown	Yasmina Brown	Yasmina
97	Duran	Paula Duran	Paula
98	Earley	Margaret Earley	Margaret
99	Horne	Elizabeth Horne	Elizabeth
89	Meastas	Bishop Meastas	Bishop
67	Stedman	Cian Stedman	Cian
87	Thomson	Kathleen Thomson	Kathleen
78	Touchstone	Joseph Touchstone	Joseph
69	Walsh	Jean Walsh	Jean
88	Walton	Gabriel Walton	Gabriel
68	Zocchi	Michele Zocchi	Michele
