framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/unionall.ddl
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/avro_nullable.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/avro_partitioned.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/hive_avro.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/orc_complex.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/sequenceFileFormat.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/fewtypes_null_compressed.ddl
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/sequenceInput.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/rcFileFormat.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/alltypes.q
framework/resources/Datasources/hive/execHive.sh framework/resources/Datasources/hive_storage/null_schemachange.ddl
