736	Baltazar	Alberto Baltazar	Alberto
744	Bidelman	Chris Bidelman	Chris
741	Ciochon	Gina Ciochon	Gina
745	Gee	Orlando Gee	Orlando
737	Higgs	Onetha Higgs	Onetha
731	Mendiola	Gladys Mendiola	Gladys
740	Montera	Hillaine Montera	Hillaine
732	Trolen	David Trolen	David
733	Vernon	Wanda Vernon	Wanda
