9	Blumberg	Brenda Blumberg	Brenda
8	Brunner	Kim Brunner	Kim
15	Cavestany	Walter Cavestany	Walter
12	Creek	Jewel Creek	Jewel
17	Marshall	Brenda Marshall	Brenda
13	Medina	Peggy Medina	Peggy
11	Murraiin	Jonathan Murraiin	Jonathan
16	Planck	Peggy Planck	Peggy
14	Rutledge	Bryan Rutledge	Bryan
