F	M	USA	Drink
F	M	USA	Food
F	M	USA	Non-Consumable
F	S	USA	Drink
F	S	USA	Food
F	S	USA	Non-Consumable
M	M	USA	Drink
M	M	USA	Food
M	M	USA	Non-Consumable
M	S	USA	Drink
M	S	USA	Food
M	S	USA	Non-Consumable
