85	Blau	Lana Blau	Lana
84	Burger	William Burger	William
65	Contreras	Whitney Contreras	Whitney
86	Derby	Donna Derby	Donna
95	Hance	Nancy Hance	Nancy
64	Harris	Clayton Harris	Clayton
75	Jones	Jay Jones	Jay
94	Magenheim	Susan Magenheim	Susan
96	Mehlert	Rhonda Mehlert	Rhonda
66	Pusedu	Boyd Pusedu	Boyd
74	Walker	Julie Walker	Julie
76	Winfrey	Gayle Winfrey	Gayle
