USA	OR	Albany	Drink	Beverages
USA	OR	Corvallis	Drink	Beverages
USA	OR	Corvallis	Drink	Dairy
USA	OR	Lebanon	Drink	Beverages
USA	OR	Lebanon	Drink	Dairy
USA	OR	Salem	Drink	Beverages
USA	OR	Woodburn	Drink	Beverages
USA	OR	Woodburn	Drink	Dairy
USA	WA	Bellingham	Drink	Beverages
USA	WA	Bellingham	Drink	Dairy
USA	WA	Yakima	Drink	Beverages
