#!/bin/bash

set -x

if [ $# -ne 5 ]
then
  echo "checklogsall needs cluster, pod, loglevel, timeout and last log message"
  exit 1
fi

cluster=$1
pod=$2
loglevel=$3
timeoutvalue=$4
lastlogmsg=$5
# echo command to provide output for debugging purposes
echo checklogsall cluster $cluster pod $pod loglevel $loglevel timeout $timeout lastlogmsg $lastlogmsg
# repeat echo command to provide output that can be matched with all.output
echo checklogsall pod $pod loglevel $loglevel timeout $timeout lastlogmsg $lastlogmsg

for i in $(kubectl get pods -n $cluster | grep $pod | awk '{print $1}')
do
  echo $i
  ./checklogs $cluster $i $loglevel $timeoutvalue "$lastlogmsg"
done

exit 0
