#!/bin/bash

set -x

cp cldbcollect.sh collect.sh

if [[ $# -ne 3 ]]
then
  echo cldbinternal needs the cluster name, the number of pods to upgrade and a timeout
  exit 1
fi

cluster=$1
numberpods=$2
timeoutvalue=$3
echo cldbinternal2 cluster $cluster number of pods $numberpods upgradecldbtimeout $timeoutvalue

errors=0

./upgradecldb $cluster $numberpods $timeoutvalue
ret=$?
if [[ $ret -gt 0 ]]
then
  echo upgrade cldb has returned error $ret
  kubectl get pods -n $cluster | grep cldb
  exit $ret
fi

./checkcldbvalid $cluster $errors 10

./checkcldbmaster $cluster $errors 10

checkcldbconnectzk $cluster $errors 10

date

exit $errors
