#!/bin/bash

set -x

if [ $# -ne 2 ]
then
  echo "getupg needs cluster and pod"
  exit 1
fi

cluster=$1
pod=$2
echo getupg cluster $cluster pod $pod

kubectl describe pods $pod -n $cluster | grep Image:
kubectl describe pods $pod -n $cluster | grep -A 14 Limits
