#!/bin/bash

set -x

date

/bin/rm collect.sh
cp zkcollect.sh collect.sh

if [[ $# -ne 3 ]]
then
  echo zkinternal needs the cluster, the number of pods to upgrade and a timeout
  exit 1
fi

cluster=$1
numberpods=$2
timeoutvalue=$3
echo zkinternal cluster $cluster number of pods $numberpods upgradezktimeout $timeoutvalue

errors=0

./upgradezk $cluster $numberpods $timeoutvalue
ret=$?
if [[ $ret -gt 0 ]]
then
  echo upgrade zk has returned error $ret
  kubectl get pods -n $cluster | grep zk
  exit $ret
fi

kubectl get pods -n $cluster -o wide

./checkcmzhealth $cluster 0 10

date

exit 0
