SELECT
  C_COUNT,
  COUNT(*) AS CUSTDIST
FROM
  (
    SELECT
      C.C_CUSTKEY,
      COUNT(O.O_ORDERKEY)
    FROM
      customer C 
      LEFT OUTER JOIN orders O 
        ON C.C_CUSTKEY = O.O_CUSTKEY
        AND O.O_COMMENT NOT LIKE '%SPECIAL%REQUESTS%'
    GROUP BY
      C.C_CUSTKEY
  ) AS ORDERS (C_CUSTKEY, C_COUNT)
GROUP BY
  C_COUNT
ORDER BY
  CUSTDIST DESC,
  C_COUNT DESC;
