ALTER SESSION SET `PLANNER.ENABLE_HASHAGG` = FALSE;
SELECT SUM(L_EXTENDEDPRICE * L_DISCOUNT) AS REVENUE 
   FROM lineitem 
	WHERE L_SHIPDATE BETWEEN DATE '1997-01-01' AND DATE '1998-01-01' 
		AND L_QUANTITY < 24 ;
ALTER SESSION SET `PLANNER.ENABLE_HASHAGG` = TRUE;
