ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = FALSE;
SELECT COUNT(*) 
  FROM (SELECT L.L_ORDERKEY, C.C_CUSTKEY 
	FROM lineitem L 
        LEFT OUTER JOIN customer C 
             ON L.L_ORDERKEY = C.C_CUSTKEY) AS FOO;
ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = TRUE;
