ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = FALSE;
SELECT COUNT(*)  
  FROM supplier S, lineitem L, orders O 
	WHERE S.S_SUPPKEY = L.L_SUPPKEY 
		AND O.O_ORDERKEY = L.L_ORDERKEY 
    	AND L.L_SHIPDATE BETWEEN DATE '1995-01-01' AND DATE '1995-12-31' ;
ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = TRUE;
