ALTER SESSION SET `PLANNER.ENABLE_HASHJOIN` = FALSE;
SELECT COUNT(*)  
  FROM supplier S 
	JOIN lineitem L ON S.S_SUPPKEY = L.L_SUPPKEY 
    JOIN orders O ON O.O_ORDERKEY = L.L_ORDERKEY
   WHERE L.L_SHIPDATE BETWEEN DATE '1995-01-01' AND DATE '1995-12-31' ;
ALTER SESSION SET `PLANNER.ENABLE_HASHJOIN` = TRUE;
