ALTER SESSION SET `PLANNER.ENABLE_HASHJOIN` = FALSE;
SELECT O.O_TOTALPRICE, L.L_ORDERKEY
   FROM orders O, lineitem L
   WHERE O.O_ORDERKEY = L.L_ORDERKEY AND O.O_TOTALPRICE > 500000.00
   ORDER BY O.O_TOTALPRICE;
ALTER SESSION SET `PLANNER.ENABLE_HASHJOIN` = TRUE;
