ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = FALSE;
SELECT P.P_PARTKEY 
   FROM part P, partsupp PS 
   WHERE P.P_PARTKEY = PS.PS_PARTKEY 
              AND P.P_SIZE = 41  
ORDER BY P.P_PARTKEY
LIMIT 20;
ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = TRUE;
