SELECT
  SUM(L.L_EXTENDEDPRICE* (1 - L.L_DISCOUNT)) AS REVENUE 
FROM
  lineitem L,
  part P 
WHERE
  P.P_PARTKEY = L.L_PARTKEY
  AND (
  (
    P.P_BRAND = 'BRAND#41'
    AND P.P_CONTAINER IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
    AND L.L_QUANTITY >= 2 AND L.L_QUANTITY <= 2 + 10
    AND P.P_SIZE BETWEEN 1 AND 5
    AND L.L_SHIPMODE IN ('AIR', 'AIR REG')
    AND L.L_SHIPINSTRUCT = 'DELIVER IN PERSON'
  )
  OR
  (
    P.P_BRAND = 'BRAND#13'
    AND P.P_CONTAINER IN ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
    AND L.L_QUANTITY >= 14 AND L.L_QUANTITY <= 14 + 10
    AND P.P_SIZE BETWEEN 1 AND 10
    AND L.L_SHIPMODE IN ('AIR', 'AIR REG')
    AND L.L_SHIPINSTRUCT = 'DELIVER IN PERSON'
  )
  OR
  (
    P.P_BRAND = 'BRAND#55'
    AND P.P_CONTAINER IN ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
    AND L.L_QUANTITY >= 23 AND L.L_QUANTITY <= 23 + 10
    AND P.P_SIZE BETWEEN 1 AND 15
    AND L.L_SHIPMODE IN ('AIR', 'AIR REG')
    AND L.L_SHIPINSTRUCT = 'DELIVER IN PERSON'
  ));
