SELECT
  C.C_NAME,
  C.C_CUSTKEY,
  O.O_ORDERKEY,
  O.O_ORDERDate,
  O.O_TOTALPRICE,
  SUM(L.L_QUANTITY)
FROM
  customer C,
  orders O,
  lineitem L
WHERE
  O.O_ORDERKEY IN (
    SELECT
      L_ORDERKEY
    FROM
      lineitem
    GROUP BY
      L_ORDERKEY HAVING
        SUM(L_QUANTITY) > 300
  )
  AND C.C_CUSTKEY = O.O_CUSTKEY
  AND O.O_ORDERKEY = L.L_ORDERKEY
GROUP BY
  C.C_NAME,
  C.C_CUSTKEY,
  O.O_ORDERKEY,
  O.O_ORDERDate,
  O.O_TOTALPRICE
ORDER BY
  O.O_TOTALPRICE DESC,
  O.O_ORDERDate
LIMIT 100;
