SELECT
  O_YEAR,
  SUM(CASE
    WHEN NATION = 'EGYPT' THEN VOLUME
    ELSE 0
  END) / SUM(VOLUME) AS MKT_SHARE
FROM
  (
    SELECT
      EXTRACT(YEAR FROM O.O_ORDERDate) AS O_YEAR,
      L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) AS VOLUME,
      N2.N_NAME AS NATION
    FROM
      part P,
      supplier S,
      lineitem L,
      orders O,
      customer C,
      nation N1,
      nation N2,
      region R
    WHERE
      P.P_PARTKEY = L.L_PARTKEY
      AND S.S_SUPPKEY = L.L_SUPPKEY
      AND L.L_ORDERKEY = O.O_ORDERKEY
      AND O.O_CUSTKEY = C.C_CUSTKEY
      AND C.C_NATIONKEY = N1.N_NATIONKEY
      AND N1.N_REGIONKEY = R.R_REGIONKEY
      AND R.R_NAME = 'MIDDLE EAST'
      AND S.S_NATIONKEY = N2.N_NATIONKEY
      AND O.O_ORDERDate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
      AND P.P_TYPE = 'PROMO BRUSHED COPPER'
  ) AS ALL_NATIONS
GROUP BY
  O_YEAR
ORDER BY
  O_YEAR;
