1	false	a	aaaabbbbcccddddeeeeffff
4	false	a	defgfhijk
6	false	c	foobarfoobar
8	false	b	aaaabbbbddddeeee
10	false	a	cdsdefdcfdef
12	false	b	ffrreeddff
14	false	b	ddffvvcdffvv
15	false	c	llkkiioollkkiioo
18	false	a	ccddffvvgghh
20	false	a	tthhyyggrrff
22	false	b	aaaaaaaabbbbb
24	false	c	hhttgffrr
26	false	a	ddvvvffffff
28	false	c	klmnopqrstu
