2	true	b	aaaabbbbcccddddeeeeffff
3	true	c	ccccddddeeefffgg
5	true	b	temp
7	true	c	foo
9	true	a	ccccddddfffrrr
11	true	c	ssccddssccdd
13	true	b	wwssaqqwwss
16	true	c	ddffrreeddffrree
17	true	c	sswweeddsswwee
19	true	a	ddrreeff
21	true	c	eebbggtt
23	true	b	ccccddddsssseeee
25	true	c	lliijjkuu
27	true	a	abcdefghij
29	true	b	vwxyzaeiou
