.*Screen.*
  .*Project.*
    .*Project.*
      .*StreamAgg.*
        .*Sort.*
          .*Project.*
            .*Project.*
              .*HashJoin.*
                .*Scan.*
                .*SelectionVectorRemover.*
                  .*Filter.*
                    .*Scan.*
