CREATE OR REPLACE VIEW Drill2461View AS SELECT CAST( NULL AS INTERVAL HOUR ) FROM INFORMATION_SCHEMA.CATALOGS LIMIT 1;
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, CHARACTER_OCTET_LENGTH, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX, NUMERIC_SCALE, DATETIME_PRECISION, INTERVAL_TYPE, INTERVAL_PRECISION FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Drill2461View';
drop view Drill2461View;
