CREATE TABLE `SelectwManyColsInProject` AS SELECT 
CAST (columns[0] as  VARCHAR(100) ) as IJPCD 
,CAST (columns[1] as  CHAR(32)) as RCVYMD 
,CAST (columns[2] as  CHAR(12)) as IJPBUNSANGRPID 
,CAST (columns[3] as  VARCHAR(48) ) as DATAID 
,CASE WHEN columns[4] = ''  THEN  NULL ELSE CAST (columns[4] as  NUMERIC(5,0))  END as SEDAINO 
,CAST (columns[5] as  CHAR(8)) as  NKDATKBN 
,CAST (columns[6] as  CHAR(4)) as  SEKYUREQKBN 
,CAST (columns[7] as  CHAR(32)) as P1IJPSYORIYMD 
,CAST (columns[8] as  CHAR(12)) as P1TRACECENTKBN 
,CAST (columns[9] as  CHAR(8)) as  P1GYOMUKBN 
,CAST (columns[10] as  CHAR(4)) as P1PCTNO 
,CAST (columns[11] as  CHAR(4)) as P1SYORIKAISU 
,CAST (columns[12] as  CHAR(4)) as P1GOKINO_C 
,CAST (columns[13] as  VARCHAR(24 )) as P1SEQNO_C 
,CAST (columns[14] as  CHAR(12))  as P1IJPEDA_3 
,CASE WHEN columns[15] = ''  THEN  NULL ELSE CAST (columns[15] as  NUMERIC(6,0))  END as P1TRACESYORITUBAN 
,CAST (columns[16] as  CHAR(32))  as P2IJPSYORIYMD 
,CAST (columns[17] as  CHAR(12))  as P2TRACECENTKBN 
,CAST (columns[18] as  CHAR(8)) as P2GYOMUKBN 
,CAST (columns[19] as  CHAR(4)) as P2PCTNO 
,CAST (columns[20] as  CHAR(4)) as P2SYORIKAISU 
,CAST (columns[21] as  CHAR(4)) as P2GOKINO_C 
,CAST (columns[22] as  VARCHAR(24 )) as P2SEQNO_C 
,CASE WHEN columns[23] = ''  THEN  NULL ELSE CAST (columns[23] as  NUMERIC(6,0))  END as P2TRACESYORITUBAN 
,CASE WHEN columns[24] = ''  THEN  NULL ELSE CAST (columns[24] as  NUMERIC(12,0))  END as OKURIJONO 
,CASE WHEN columns[25] = ''  THEN  NULL ELSE CAST (columns[25] as  NUMERIC(11,0))  END as SEKYUSAKCSTMNO_EDATK 
,CASE WHEN columns[26] = ''  THEN  NULL ELSE CAST (columns[26] as  NUMERIC(5,0))  END as SPTSETNO 
,CASE WHEN columns[27] = ''  THEN  NULL ELSE CAST (columns[27] as  NUMERIC(2,0))  END as SPTSETNOEDA 
,CAST (columns[28] as  CHAR(4)) as ISHORYUKBN 
,CAST (columns[29] as  CHAR(4)) as RCVHORYUKBN 
,CAST (columns[30] as  CHAR(4)) as GENSYUHORYUKBN 
,CAST (columns[31] as  CHAR(4)) as HASSOYOYAKUHORYUKBN 
,CASE WHEN columns[32] = ''  THEN  NULL ELSE CAST (columns[32] as  NUMERIC(3,0))  END as BETUSEKYUKANRIID 
,CASE WHEN columns[33] = ''  THEN  NULL ELSE CAST (columns[33] as  NUMERIC(3,0))  END as ERRCD 
,CAST (columns[34] as  CHAR(32))  as DATSYUSEIYMD 
,CAST (columns[35] as  CHAR(32))  as DATSYUSEITIME 
,CASE WHEN columns[36] = ''  THEN  NULL ELSE CAST (columns[36] as  NUMERIC(18,0))  END as EXCLCNT 
,CAST (columns[37] as  CHAR(4)) as ZERODENKBN 
,CAST (columns[38] as  CHAR(4)) as KOGUTSEKYUKBN_ATESAKIKBN 
,CAST (columns[39] as  CHAR(4)) as KARISMEHAKKBN 
,CAST (columns[40] as  CHAR(8)) as JTKSAKSEIKBN 
,CAST (columns[41] as  CHAR(4)) as KOSINFKKBN 
,CAST (columns[42] as  CHAR(32))  as HASSOHAITAYMD 
,CAST (columns[43] as  VARCHAR(16 )) as SYUKATENCD 
,CAST (columns[44] as  VARCHAR(8) ) as SYUKATENCDEDA 
,CAST (columns[45] as  VARCHAR(16 )) as CYATENCD 
,CAST (columns[46] as  VARCHAR(8) ) as CYATENCDEDA 
,CAST (columns[47] as  VARCHAR(12 )) as ATUKAIBINSCD 
,CAST (columns[48] as  CHAR(8)) as DATSYUBEKBN 
,CAST (columns[49] as  VARCHAR(56 )) as NISOTEL 
,CAST (columns[50] as  VARCHAR(56 )) as NIUKTEL 
,CAST (columns[51] as  VARCHAR(28 )) as NKDRVCD 
,CAST (columns[52] as  VARCHAR(64 )) as CSTMKANRINO 
,CASE WHEN columns[53] = ''  THEN  NULL ELSE CAST (columns[53] as  NUMERIC(11,0))  END as NISOCSTMNO_EDATK 
,CASE WHEN columns[54] = ''  THEN  NULL ELSE CAST (columns[54] as  NUMERIC(11,0))  END as NIUKCSTMNO_EDATK 
,CASE WHEN columns[55] = ''  THEN  NULL ELSE CAST (columns[55] as  NUMERIC(11,0))  END as TANHATTOGOSAKCSTMNO_EDATK 
,CAST (columns[56] as  CHAR(4)) as SEKYUHOKANDATUMKBN 
,CAST (columns[57] as  CHAR(4)) as KOGUTSEKYUDATSYUBE 
,CASE WHEN columns[58] = ''  THEN  NULL ELSE CAST (columns[58] as  NUMERIC(13,0))  END as KOGUTSEKYUATESAKICD 
,CAST (columns[59] as  VARCHAR(16 )) as HATSSANHOKOKUTENCD 
,CAST (columns[60] as  VARCHAR(8) ) as HATSSANHOKOKUTENCDEDA 
,CAST (columns[61] as  VARCHAR(16 )) as CYASSANHOKOKUTENCD 
,CAST (columns[62] as  VARCHAR(8) ) as CYASSANHOKOKUTENCDEDA 
,CAST (columns[63] as  VARCHAR(16 )) as SEKYUTENCD 
,CAST (columns[64] as  VARCHAR(8) ) as SEKYUTENCDEDA 
,CAST (columns[65] as  CHAR(12))  as MEISAIKEITAIKBN 
,CAST (columns[66] as  CHAR(12))  as SEKYUKEITAI2KBN 
,CAST (columns[67] as  VARCHAR(12 )) as SEKYUREQSAKHSTCD 
,CAST (columns[68] as  CHAR(32))  as EGYSIENDATSNDDD 
,CAST (columns[69] as  CHAR(32))  as NKKJOYMD 
,CAST (columns[70] as  CHAR(24))  as NKKJOYYMM 
,CAST (columns[71] as  CHAR(4)) as KJOKBN 
,CASE WHEN columns[72] = ''  THEN  NULL ELSE CAST (columns[72] as  NUMERIC(11,1))  END as SOJYURYO 
,CAST (columns[73] as  CHAR(8)) as SOJYURYOKBN 
,CASE WHEN columns[74] = ''  THEN  NULL ELSE CAST (columns[74] as  NUMERIC(11,0))  END as SOKOSU11 
,CASE WHEN columns[75] = ''  THEN  NULL ELSE CAST (columns[75] as  NUMERIC(11,1))  END as MEISAIJYURYO1 
,CASE WHEN columns[76] = ''  THEN  NULL ELSE CAST (columns[76] as  NUMERIC(11,1))  END as MEISAIJYURYO2 
,CASE WHEN columns[77] = ''  THEN  NULL ELSE CAST (columns[77] as  NUMERIC(11,1))  END as MEISAIJYURYO3 
,CASE WHEN columns[78] = ''  THEN  NULL ELSE CAST (columns[78] as  NUMERIC(11,1))  END as MEISAIJYURYO4 
,CASE WHEN columns[79] = ''  THEN  NULL ELSE CAST (columns[79] as  NUMERIC(11,1))  END as MEISAIJYURYO5 
,CASE WHEN columns[80] = ''  THEN  NULL ELSE CAST (columns[80] as  NUMERIC(11,1))  END as MEISAIJYURYO6 
,CASE WHEN columns[81] = ''  THEN  NULL ELSE CAST (columns[81] as  NUMERIC(11,1))  END as MEISAIJYURYO7 
,CASE WHEN columns[82] = ''  THEN  NULL ELSE CAST (columns[82] as  NUMERIC(11,1))  END as MEISAIJYURYO8 
,CAST (columns[83] as  CHAR(8)) as MEISAIJYURYOKBN1 
,CAST (columns[84] as  CHAR(8)) as MEISAIJYURYOKBN2 
,CAST (columns[85] as  CHAR(8)) as MEISAIJYURYOKBN3 
,CAST (columns[86] as  CHAR(8)) as MEISAIJYURYOKBN4 
,CAST (columns[87] as  CHAR(8)) as MEISAIJYURYOKBN5 
,CAST (columns[88] as  CHAR(8)) as MEISAIJYURYOKBN6 
,CAST (columns[89] as  CHAR(8)) as MEISAIJYURYOKBN7 
,CAST (columns[90] as  CHAR(8)) as MEISAIJYURYOKBN8 
,CASE WHEN columns[91] = ''  THEN  NULL ELSE CAST (columns[91] as  NUMERIC(11,0))  END as MEISAIKOSU1 
,CASE WHEN columns[92] = ''  THEN  NULL ELSE CAST (columns[92] as  NUMERIC(11,0))  END as MEISAIKOSU2 
,CASE WHEN columns[93] = ''  THEN  NULL ELSE CAST (columns[93] as  NUMERIC(11,0))  END as MEISAIKOSU3 
,CASE WHEN columns[94] = ''  THEN  NULL ELSE CAST (columns[94] as  NUMERIC(11,0))  END as MEISAIKOSU4 
,CASE WHEN columns[95] = ''  THEN  NULL ELSE CAST (columns[95] as  NUMERIC(11,0))  END as MEISAIKOSU5 
,CASE WHEN columns[96] = ''  THEN  NULL ELSE CAST (columns[96] as  NUMERIC(11,0))  END as MEISAIKOSU6 
,CASE WHEN columns[97] = ''  THEN  NULL ELSE CAST (columns[97] as  NUMERIC(11,0))  END as MEISAIKOSU7 
,CASE WHEN columns[98] = ''  THEN  NULL ELSE CAST (columns[98] as  NUMERIC(11,0))  END as MEISAIKOSU8 
,CASE WHEN columns[99] = ''  THEN  NULL ELSE CAST (columns[99] as  NUMERIC(13,0))  END as DAIBITESURKIN 
,CASE WHEN columns[100] = ''  THEN NULL ELSE CAST (columns[100] as  NUMERIC(13,0))  END as HOKENRKIN 
,CASE WHEN columns[101] = ''  THEN NULL ELSE CAST (columns[101] as  NUMERIC(13,0))  END as SEKYUCYUKEIRKIN 
,CAST (columns[102] as  CHAR(8))  as TATEKAEKBN1 
,CAST (columns[103] as  CHAR(8))  as TATEKAEKBN2 
,CASE WHEN columns[104] = ''  THEN NULL ELSE CAST (columns[104] as  NUMERIC(13,0))  END as TATEKAEKIN1 
,CASE WHEN columns[105] = ''  THEN NULL ELSE CAST (columns[105] as  NUMERIC(13,0))  END as TATEKAEKIN2 
,CAST (columns[106] as  CHAR(8))  as FUKARKINKBN1 
,CAST (columns[107] as  CHAR(8))  as FUKARKINKBN2 
,CAST (columns[108] as  CHAR(8))  as FUKARKINKBN3 
,CAST (columns[109] as  CHAR(8))  as FUKARKINKBN4 
,CASE WHEN columns[110] = ''  THEN NULL ELSE CAST (columns[110] as  NUMERIC(13,0))  END as FUKARKIN1 
,CASE WHEN columns[111] = ''  THEN NULL ELSE CAST (columns[111] as  NUMERIC(13,0))  END as FUKARKIN2 
,CASE WHEN columns[112] = ''  THEN NULL ELSE CAST (columns[112] as  NUMERIC(13,0))  END as FUKARKIN3 
,CASE WHEN columns[113] = ''  THEN NULL ELSE CAST (columns[113] as  NUMERIC(13,0))  END as FUKARKIN4 
,CAST (columns[114] as  CHAR(12))  as ZATUSYUNYUKBN 
,CASE WHEN columns[115] = ''  THEN NULL ELSE CAST (columns[115] as  NUMERIC(13,0))  END as KOKURKINGAKU 
,CASE WHEN columns[116] = ''  THEN NULL ELSE CAST (columns[116] as  NUMERIC(13,0))  END as FUNADAIKIN 
,CASE WHEN columns[117] = ''  THEN NULL ELSE CAST (columns[117] as  NUMERIC(13,0))  END as UNTINTOTALKINGAKU 
,CASE WHEN columns[118] = ''  THEN NULL ELSE CAST (columns[118] as  NUMERIC(13,0))  END as KARIKANYOUNTINTOTALKIN  
,CASE WHEN columns[119] = ''  THEN NULL ELSE CAST (columns[119] as  NUMERIC(13,0))  END as UNTINSEKYUKINGAKU 
,CAST (columns[120] as  CHAR(4))  as NAIZEIKBN 
,CAST (columns[121] as  CHAR(4))  as EDACSTMNEZKBN 
,CAST (columns[122] as  CHAR(4))  as TOTALMEISAKAKIKOMUNTINKBN 
,CAST (columns[123] as  CHAR(8))  as SEKYUDATHASSEGENKBN 
,CAST (columns[124] as  CHAR(4))  as CAMPAIGNKBN 
,CASE WHEN columns[125] = ''  THEN NULL ELSE CAST (columns[125] as  NUMERIC(13,0))  END as SSANCYUKEIRKIN 
,CASE WHEN columns[126] = ''  THEN NULL ELSE CAST (columns[126] as  NUMERIC(13,0))  END as SSANUNTINTOTALKIN 
,CAST (columns[127] as  CHAR(4))  as IMG24KENMEISAIPRTKBN 
,CASE WHEN columns[128] = ''  THEN NULL ELSE CAST (columns[128] as  NUMERIC(13,0))  END as SSANTOTALKIN 
,CAST (columns[129] as  CHAR(8))  as SPTHASSEIYOKENKBN 
,CASE WHEN columns[130] = ''  THEN NULL ELSE CAST (columns[130] as  NUMERIC(13,0))  END as MEISAIKOKURKIN1 
,CASE WHEN columns[131] = ''  THEN NULL ELSE CAST (columns[131] as  NUMERIC(13,0))  END as MEISAIKOKURKIN2 
,CASE WHEN columns[132] = ''  THEN NULL ELSE CAST (columns[132] as  NUMERIC(13,0))  END as MEISAIKOKURKIN3 
,CASE WHEN columns[133] = ''  THEN NULL ELSE CAST (columns[133] as  NUMERIC(13,0))  END as MEISAIKOKURKIN4 
,CASE WHEN columns[134] = ''  THEN NULL ELSE CAST (columns[134] as  NUMERIC(13,0))  END as MEISAIKOKURKIN5 
,CASE WHEN columns[135] = ''  THEN NULL ELSE CAST (columns[135] as  NUMERIC(13,0))  END as MEISAIKOKURKIN6 
,CASE WHEN columns[136] = ''  THEN NULL ELSE CAST (columns[136] as  NUMERIC(13,0))  END as MEISAIKOKURKIN7 
,CASE WHEN columns[137] = ''  THEN NULL ELSE CAST (columns[137] as  NUMERIC(13,0))  END as MEISAIKOKURKIN8 
,CAST (columns[138] as  CHAR(4))  as KAKIKOMIUNTINKBN 
,CAST (columns[139] as  CHAR(8))  as TASYADENCD 
,CAST (columns[140] as  CHAR(4))  as NEZREQKBN 
,CAST (columns[141] as  VARCHAR(512)) as KOSINPGMID 
,CAST (columns[142] as  CHAR(4))  as DATMASSYKBN 
,CAST (columns[143] as  CHAR(16))  as P1ENTRYSYACD 
,CAST (columns[144] as  CHAR(16))  as P2ENTRYSYACD 
,CAST (columns[145] as  CHAR(16))  as P1VERIFYENTRYSYACD 
,CAST (columns[146] as  CHAR(16))  as P2VERIFYENTRYSYACD 
,CAST (columns[147] as  CHAR(28))  as OLAFCYAYOENTRYCD 
,CAST (columns[148] as  CHAR(4))  as CYAKUBARAIHORYUKBN 
,CAST (columns[149] as  CHAR(4))  as CYATENKAKUTEIKBN 
,CAST (columns[150] as  CHAR(12))  as SYUSEIJIYKBN 
,CAST (columns[151] as  CHAR(4))  as MSTTOROKUMTHORYUKBN 
,CAST (columns[152] as  VARCHAR(512)) as SYUSEIMASSYTRMID 
,CAST (columns[153] as  CHAR(4))  as EGYSIENSNDKBN 
,CAST (columns[154] as  CHAR(4))  as HASSOCYAKUBARAISHIKBN 
,CAST (columns[155] as  CHAR(24))  as OCRKBN 
,CASE WHEN columns[156] = ''  THEN NULL ELSE CAST (columns[156] as  NUMERIC(11,0))  END as CSTMNO_EDATK 
,CAST (columns[157] as  CHAR(4))  as CSTMNOCHK 
,CAST (columns[158] as  CHAR(4))  as SPTTOKNO 
,CAST (columns[159] as  CHAR(4))  as SSANRITHENKOKBN 
,CASE WHEN columns[160] = ''  THEN NULL ELSE CAST (columns[160] as  NUMERIC(13,0))  END as SYUKTENKAKAKARIHANGOSYACD 
,CASE WHEN columns[161] = ''  THEN NULL ELSE CAST (columns[161] as  NUMERIC(13,0))  END as CYATENKAKAKARIHANGOSYACD 
,CAST (columns[162] as  VARCHAR(44)) as CYATENJIS11KETATIKCD 
,CAST (columns[163] as  CHAR(4))  as NIUKKAKUTEIKBN 
,CAST (columns[164] as  CHAR(4))  as NISOKAKUTEIKBN 
,CAST (columns[165] as  CHAR(4))  as NIUKHOJINKAKUKBN 
,CAST (columns[166] as  CHAR(4))  as NIUKHOJINKOJINSHIKBN 
,CAST (columns[167] as  CHAR(4))  as NISOHOJINKOJINSHIKBN 
,CAST (columns[168] as  CHAR(4))  as KMTIMGHJKBN 
,CAST (columns[169] as  CHAR(4))  as MEISAIKEISANKBN1 
,CAST (columns[170] as  CHAR(4))  as MEISAIKEISANKBN2 
,CAST (columns[171] as  CHAR(4))  as MEISAIKEISANKBN3 
,CAST (columns[172] as  CHAR(4))  as MEISAIKEISANKBN4 
,CAST (columns[173] as  CHAR(4))  as MEISAIKEISANKBN5 
,CAST (columns[174] as  CHAR(4))  as MEISAIKEISANKBN6 
,CAST (columns[175] as  CHAR(4))  as MEISAIKEISANKBN7 
,CAST (columns[176] as  CHAR(4))  as MEISAIKEISANKBN8 
,CASE WHEN columns[177] = ''  THEN NULL ELSE CAST (columns[177] as  NUMERIC(13,0))  END as MEISAIUNTIN1 
,CASE WHEN columns[178] = ''  THEN NULL ELSE CAST (columns[178] as  NUMERIC(13,0))  END as MEISAIUNTIN2 
,CASE WHEN columns[179] = ''  THEN NULL ELSE CAST (columns[179] as  NUMERIC(13,0))  END as MEISAIUNTIN3 
,CASE WHEN columns[180] = ''  THEN NULL ELSE CAST (columns[180] as  NUMERIC(13,0))  END as MEISAIUNTIN4 
,CASE WHEN columns[181] = ''  THEN NULL ELSE CAST (columns[181] as  NUMERIC(13,0))  END as MEISAIUNTIN5 
,CASE WHEN columns[182] = ''  THEN NULL ELSE CAST (columns[182] as  NUMERIC(13,0))  END as MEISAIUNTIN6 
,CASE WHEN columns[183] = ''  THEN NULL ELSE CAST (columns[183] as  NUMERIC(13,0))  END as MEISAIUNTIN7 
,CASE WHEN columns[184] = ''  THEN NULL ELSE CAST (columns[184] as  NUMERIC(13,0))  END as MEISAIUNTIN8 
,CASE WHEN columns[185] = ''  THEN NULL ELSE CAST (columns[185] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN1 
,CASE WHEN columns[186] = ''  THEN NULL ELSE CAST (columns[186] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN2 
,CASE WHEN columns[187] = ''  THEN NULL ELSE CAST (columns[187] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN3 
,CASE WHEN columns[188] = ''  THEN NULL ELSE CAST (columns[188] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN4 
,CASE WHEN columns[189] = ''  THEN NULL ELSE CAST (columns[189] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN5 
,CASE WHEN columns[190] = ''  THEN NULL ELSE CAST (columns[190] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN6 
,CASE WHEN columns[191] = ''  THEN NULL ELSE CAST (columns[191] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN7 
,CASE WHEN columns[192] = ''  THEN NULL ELSE CAST (columns[192] as  NUMERIC(13,0))  END as MEISAIKEISANUNTIN8 
,CASE WHEN columns[193] = ''  THEN NULL ELSE CAST (columns[193] as  NUMERIC(13,0))  END as DAIBIKIKIN 
,CAST (columns[194] as  CHAR(4))  as DAIBITESUKAKIKOMIKBN 
,CAST (columns[195] as  CHAR(4))  as DAIBITESUBUNPAIRTHENKOKBN 
,CASE WHEN columns[196] = ''  THEN NULL ELSE CAST (columns[196] as  NUMERIC(13,0))  END as DAIBITESUHATTORIFUNKIN  
,CASE WHEN columns[197] = ''  THEN NULL ELSE CAST (columns[197] as  NUMERIC(13,0))  END as DAIBITESUCYATORIFUNKIN  
,CASE WHEN columns[198] = ''  THEN NULL ELSE CAST (columns[198] as  NUMERIC(13,0))  END as DAIBITESUHONBUTORIFUNKIN 
,CASE WHEN columns[199] = ''  THEN NULL ELSE CAST (columns[199] as  NUMERIC(13,0))  END as HOKENKIN 
,CAST (columns[200] as  CHAR(4))  as HOKENRYOKAKIKOMIKBN 
,CAST (columns[201] as  CHAR(4))  as CYUKEIKAKIKOMIKBN 
,CAST (columns[202] as  CHAR(4))  as TATEKAEKAKIKOMIKBN1 
,CAST (columns[203] as  CHAR(4))  as TATEKAEKAKIKOMIKBN2 
,CAST (columns[204] as  CHAR(4))  as FUKARKINKAKIKOMIKBN1 
,CAST (columns[205] as  CHAR(4))  as FUKARKINKAKIKOMIKBN2 
,CAST (columns[206] as  CHAR(4))  as FUKARKINKAKIKOMIKBN3 
,CAST (columns[207] as  CHAR(4))  as FUKARKINKAKIKOMIKBN4 
,CAST (columns[208] as  CHAR(4))  as KOKURYOKAKIKOMIKBN 
,CASE WHEN columns[209] = ''  THEN NULL ELSE CAST (columns[209] as  NUMERIC(13,0))  END as KAKIKOMIUNTINTOTALKIN  
,CASE WHEN columns[210] = ''  THEN NULL ELSE CAST (columns[210] as  NUMERIC(13,0))  END as KEISANUNTINTOTALKIN 
,CAST (columns[211] as  CHAR(4))  as TOKKBN 
,CAST (columns[212] as  CHAR(8))  as HATTITAICD 
,CAST (columns[213] as  CHAR(8))  as CYAKUTAICD 
,CAST (columns[214] as  CHAR(4))  as UNTINHYOKEITAIKBN 
,CAST (columns[215] as  CHAR(8))  as KEIYAKKEITAIKBN 
,CAST (columns[216] as  CHAR(32))  as UNTINHYOSAKSEIYMD 
,CAST (columns[217] as  CHAR(16))  as BUMONCD 
,CAST (columns[218] as  CHAR(4))  as SGWDENKBN 
,CAST (columns[219] as  CHAR(4))  as HOKENKBN 
,CAST (columns[220] as  VARCHAR(16)) as NINUSITOROKUTENCD 
,CAST (columns[221] as  VARCHAR(8 )) as NINUSITOROKUTENCDEDA 
,CASE WHEN columns[222] = ''  THEN NULL ELSE CAST (columns[222] as  NUMERIC(13,0))  END as SSANDAIBITESURKINGAKU  
,CASE WHEN columns[223] = ''  THEN NULL ELSE CAST (columns[223] as  NUMERIC(13,0))  END as SSANHOKENRKINGAKU 
,CASE WHEN columns[224] = ''  THEN NULL ELSE CAST (columns[224] as  NUMERIC(13,0))  END as SSANTATEKAEKIN1 
,CASE WHEN columns[225] = ''  THEN NULL ELSE CAST (columns[225] as  NUMERIC(13,0))  END as SSANTATEKAEKIN2 
,CASE WHEN columns[226] = ''  THEN NULL ELSE CAST (columns[226] as  NUMERIC(13,0))  END as SSANFUKARKIN1 
,CASE WHEN columns[227] = ''  THEN NULL ELSE CAST (columns[227] as  NUMERIC(13,0))  END as SSANFUKARKIN2 
,CASE WHEN columns[228] = ''  THEN NULL ELSE CAST (columns[228] as  NUMERIC(13,0))  END as SSANFUKARKIN3 
,CASE WHEN columns[229] = ''  THEN NULL ELSE CAST (columns[229] as  NUMERIC(13,0))  END as SSANFUKARKIN4 
,CAST (columns[230] as  CHAR(4))  as UNTINTOTALNEBIKKBN 
,CAST (columns[231] as  CHAR(4))  as CYUKEIRYONEBIKKBN 
,CAST (columns[232] as  CHAR(4))  as DAIBITESUNEBIKKBN 
,CAST (columns[233] as  CHAR(4))  as HOKENRYONEBIKKBN 
,CAST (columns[234] as  CHAR(4))  as TATEKAEKINNEBIKKBN1 
,CAST (columns[235] as  CHAR(4))  as TATEKAEKINNEBIKKBN2 
,CAST (columns[236] as  CHAR(4))  as FUKARKINNEBIKKBN1 
,CAST (columns[237] as  CHAR(4))  as FUKARKINNEBIKKBN2 
,CAST (columns[238] as  CHAR(4))  as FUKARKINNEBIKKBN3 
,CAST (columns[239] as  CHAR(4))  as FUKARKINNEBIKKBN4 
,CAST (columns[240] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN1 
,CAST (columns[241] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN2 
,CAST (columns[242] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN3 
,CAST (columns[243] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN4 
,CAST (columns[244] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN5 
,CAST (columns[245] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN6 
,CAST (columns[246] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN7 
,CAST (columns[247] as  CHAR(4))  as MEISAIJYURYOKAKIKOMIKBN8 
,CAST (columns[248] as  VARCHAR(12)) as SEKYUHSTCENTCD 
,CAST (columns[249] as  CHAR(4))  as DAIBINAIZEIKBN 
FROM dfs.ctas.`custmimic.csv`;
SELECT * FROM SelectwManyColsInProject;
DROP TABLE SelectwManyColsInProject;
