select columns[0],
columns[1],
columns[2],
columns[3],
columns[4],
columns[5],
columns[6],
columns[7],
columns[8],
columns[9],
columns[10],
columns[11],
columns[12],
columns[13],
columns[14],
columns[15]
from `/drill/testdata/text_storage/lineitem`;