SELECT
   TIMESTAMPDIFF(SQL_TSI_HOUR, CAST(TIMESTAMPADD(SQL_TSI_MINUTE, -600, CAST(o_orderdate AS TIMESTAMP)) AS TIMESTAMP), CAST(o_orderdate AS TIMESTAMP)) AS num_of_hours
FROM
  orders
WHERE
  o_orderkey = 3;