.*Screen.*
  .*Project.*
    .*Project.*
        .*HashAgg.*
          .*Project.*
            .*Project.*
              .*HashJoin.*
                .*Scan.*
                .*SelectionVectorRemover.*
                  .*Filter.*
                    .*Scan.*
