.*Screen.*
  .*Project.*
    .*Project.*
      .*Project.*
        .*StreamAgg.*
          .*Sort.*
            .*Project.*
              .*Project.*
                .*HashJoin.*
                  .*Scan.*
                  .*SelectionVectorRemover.*
                    .*Filter.*
                     .*Project.*
                        .*Scan.*
