.*Screen
  .*Project
    .*Project
      .*Project
        .*SelectionVectorRemover
          .*Filter
            .*HashAgg
              .*Project
                .*Project
                  .*HashJoin
                    .*Scan
                    .*SelectionVectorRemover
                       .*Filter
                        .*Scan
