ALTER SESSION SET `PLANNER.ENABLE_STREAMAGG` = FALSE;
SELECT P.P_MFGR AS MFGR, COUNT(*) AS MYCOUNT 
   FROM part P 
   WHERE P.P_SIZE < 100 AND P.P_TYPE LIKE '%NICKEL'
 GROUP BY P.P_MFGR 
 ORDER BY MYCOUNT;
ALTER SESSION SET `PLANNER.ENABLE_STREAMAGG` = TRUE;
