ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = FALSE;
SELECT COUNT(*) 
   FROM (SELECT L.L_QUANTITY 
	FROM lineitem L, partsupp PS 
		WHERE L.L_PARTKEY = PS.PS_PARTKEY 
        AND L.L_SUPPKEY = PS.PS_SUPPKEY) AS FOO;
ALTER SESSION SET `PLANNER.ENABLE_MERGEJOIN` = TRUE;
