ALTER SESSION SET `PLANNER.ENABLE_HASHJOIN` = FALSE;
SELECT COUNT(*)
  FROM (SELECT C.C_CUSTKEY
	FROM customer C, orders O
	WHERE C.C_CUSTKEY = O.O_CUSTKEY) AS FOO;
ALTER SESSION SET `PLANNER.ENABLE_HASHJOIN` = TRUE;
