create or replace view `dfs_test.tpcds_sf1_parquet`.store_v as select
cast( s_store_sk as integer)  as s_store_sk,
cast( s_store_id as varchar(200))  as s_store_id,
cast( s_rec_start_date as date)  as s_rec_start_date,
cast( s_rec__date as date)  as s_rec__date,
cast( s_closed_date_sk as integer)  as s_closed_date_sk,
cast( s_store_name as varchar(200))  as s_store_name,
cast( s_number_employees as integer)  as s_number_employees,
cast( s_floor_space as integer)  as s_floor_space,
cast( s_hours as varchar(200))  as s_hours,
cast( s_manager as varchar(200))  as s_manager,
cast( s_market_id as integer)  as s_market_id,
cast( s_geography_class as varchar(200))  as s_geography_class,
cast( s_market_desc as varchar(200))  as s_market_desc,
cast( s_market_manager as varchar(200))  as s_market_manager,
cast( s_division_id as integer)  as s_division_id,
cast( s_division_name as varchar(200))  as s_division_name,
cast( s_company_id as integer)  as s_company_id,
cast( s_company_name as varchar(200))  as s_company_name,
cast( s_street_number as varchar(200))  as s_street_number,
cast( s_street_name as varchar(200))  as s_street_name,
cast( s_street_type as varchar(200))  as s_street_type,
cast( s_suite_number as varchar(200))  as s_suite_number,
cast( s_city as varchar(200))  as s_city,
cast( s_county as varchar(200))  as s_county,
cast( s_state as varchar(200))  as s_state,
cast( s_zip as varchar(200))  as s_zip,
cast( s_country as varchar(200))  as s_country,
cast( s_gmt_offset as double)  as s_gmt_offset,
cast( s_tax_precentage as double)  as s_tax_precentage
from dfs_test.`/drill/testdata/tpcds_sf1/parquet/store`;

create or replace view `dfs_test.tpcds_sf1_parquet`.store_sales_v as select
cast( ss_sold_date_sk as integer)  as ss_sold_date_sk,
cast( ss_sold_time_sk as integer)  as ss_sold_time_sk,
cast( ss_item_sk as integer)  as ss_item_sk,
cast( ss_customer_sk as integer)  as ss_customer_sk,
cast( ss_cdemo_sk as integer)  as ss_cdemo_sk,
cast( ss_hdemo_sk as integer)  as ss_hdemo_sk,
cast( ss_addr_sk as integer)  as ss_addr_sk,
cast( ss_store_sk as integer)  as ss_store_sk,
cast( ss_promo_sk as integer)  as ss_promo_sk,
cast( ss_ticket_number as integer)  as ss_ticket_number,
cast( ss_quantity as integer)  as ss_quantity,
cast( ss_wholesale_cost as double)  as ss_wholesale_cost,
cast( ss_list_price as double)  as ss_list_price,
cast( ss_sales_price as double)  as ss_sales_price,
cast( ss_ext_discount_amt as double)  as ss_ext_discount_amt,
cast( ss_ext_sales_price as double)  as ss_ext_sales_price,
cast( ss_ext_wholesale_cost as double)  as ss_ext_wholesale_cost,
cast( ss_ext_list_price as double)  as ss_ext_list_price,
cast( ss_ext_tax as double)  as ss_ext_tax,
cast( ss_coupon_amt as double)  as ss_coupon_amt,
cast( ss_net_paid as double)  as ss_net_paid,
cast( ss_net_paid_inc_tax as double)  as ss_net_paid_inc_tax,
cast( ss_net_profit as double)  as ss_net_profit
from dfs_test.`/drill/testdata/tpcds_sf1/parquet/store_sales`;

create or replace view `dfs_test.tpcds_sf1_parquet`.customer_v as select
cast(c_customer_sk as integer)  as c_customer_sk,
cast(c_customer_id as varchar(200))  as c_customer_id,
cast(c_current_cdemo_sk as integer)  as c_current_cdemo_sk,
cast(c_current_hdemo_sk as integer)  as c_current_hdemo_sk,
cast(c_current_addr_sk as integer)  as c_current_addr_sk,
cast(c_first_shipto_date_sk as integer)  as c_first_shipto_date_sk,
cast(c_first_sales_date_sk as integer)  as c_first_sales_date_sk,
cast(c_salutation as varchar(200))  as c_salutation,
cast(c_first_name as varchar(200))  as c_first_name,
cast(c_last_name as varchar(200))  as c_last_name,
cast(c_preferred_cust_flag as varchar(200))  as c_preferred_cust_flag,
cast(c_birth_day as integer)  as c_birth_day,
cast(c_birth_month as integer)  as c_birth_month,
cast(c_birth_year as integer)  as c_birth_year,
cast(c_birth_country as varchar(200))  as c_birth_country,
cast(c_login as varchar(200))  as c_login,
cast(c_email_address as varchar(200))  as c_email_address,
cast(c_last_review_date as varchar(200))  as c_last_review_date
from dfs_test.`/drill/testdata/tpcds_sf1/parquet/customer`;
